flipperzero-rs/flipperzero-rs

crates/flipperzero/src/furi/io.rs
crates/flipperzero/src/furi/message_queue.rs
crates/flipperzero/src/furi/mod.rs
crates/sys/src/furi/base.rs
crates/sys/src/furi/message_queue.rs
crates/sys/src/furi/mod.rs

Rebased from #1.
```rust
let queue: MessageQueue<msg> = MessageQueue::new(8);
write!(&mut stdout, "Queue capacity/count/space: {:?}/{:?}/{:?}\r\n", queue.capacity(), queue.len(), queue.space()).unwrap();
queue.put(msg(69), 9999999).unwrap();
write!(&mut stdout, "Queue capacity/count/space: {:?}/{:?}/{:?}\r\n", queue.capacity(), queue.len(), queue.space()).unwrap();
let output = queue.get(9999999);
write!(&mut stdout, "Read back: {:?}\r\n", output.unwrap()).unwrap();
write!(&mut stdout, "Queue capacity/count/space: {:?}/{:?}/{:?}\r\n", queue.capacity(), queue.len(), queue.space()).unwrap();
stdout.flush().unwrap();
```

0.2-dev: Implement message_queue, fix Stdout.flush

---

crates/sys/src/view_port.rs

I tested something like this:
```rust
pub extern "C" fn input_callback(event: *mut InputEvent, context: *mut c_void) {
unsafe {
core::mem::transmute::<*mut c_void, &MessageQueue<msg>>(context).put(msg((*event).clone()), 9999);
}
}
fn main {
let queue: MessageQueue<msg> = MessageQueue::new(8);
// ...
sys::view_port::input_callback_set(view_port, input_callback, core::mem::transmute(&queue));
// ...
loop {
let evt = queue.get(9999999).unwrap().0;
write!(&mut stdout, "Event: {}\r\n", evt).unwrap();
stdout.flush().unwrap();
if evt.key == keys::BACK {
break;
}
}
// ...
}
```
With output:

0.2-dev: Implement InputEvent

---

crates/flipperzero/src/alloc.rs
crates/flipperzero/src/furi_alloc.rs
crates/flipperzero/src/lib.rs

Added bindings to the furi memory allocator. 
Alloc crate should be usable now.
How to use: do nothing, #[global_allocator] will automatically wire it.
Comments:
- Tested on @twitchyliquid64 fz-rust example + vec/string usage.
- Current `on_oom` implementation is rather simple, feel free to propose what should be there or freely modify it. I'm not sure flipper would be able to properly allocate c_string on OOM (in tests I just see that somewhere furi_check fails and flipper reboots)

Memory allocator

---

Cargo.toml
crates/alloc/.gitignore
crates/alloc/Cargo.toml
crates/alloc/README.md
crates/alloc/src/lib.rs
crates/flipperzero/src/lib.rs
crates/sys/src/lfrfid.rs
crates/sys/src/lib.rs
crates/sys/src/toolbox/mod.rs
crates/sys/src/toolbox/protocols.rs

Could use some advice on appropriate types, in particular what to do about `PROTOCOLS_MAX`.
I was able to open the front door of my apartment complex with this code:
```rust
let dict = protocol_dict_alloc(&LFRFID_PROTOCOLS, PROTOCOLS_MAX);
let protocol_id = protocol_dict_get_protocol_by_name(dict, sys::c_string!("H10301"));
let mut data: [u8; 3] = [<REDACTED>];
protocol_dict_set_data(dict, protocol_id, data.as_ptr(), 3);
let rf_worker = lfrfid_worker_alloc(dict);
lfrfid_worker_start_thread(rf_worker);
lfrfid_worker_emulate_start(rf_worker, protocol_id);
// wait for user input
lfrfid_worker_stop(rf_worker);
lfrfid_worker_stop_thread(rf_worker);
lfrfid_worker_free(rf_worker);
protocol_dict_free(dict);
```

0.2-dev: LF-RFID emulation support

---

.github/workflows/rust.yml

This currently pulls in nightly so that we can build the `flipperzero-alloc` crate.

Add Rust CI workflow

---

crates/sys/src/gui/elements.rs
crates/sys/src/gui/mod.rs
crates/sys/src/gui/variable_item_list.rs
crates/sys/src/gui/view.rs

The VIL in particular lets you make pretty config menus:
Whereas the elements API is just for consistent buttons and rendering and stuff:

Implement bindings for elements & variable_item_list widgets

---

tools/src/bin/generate-bindings.rs

I've simply added the x86 path to Linux for consistency reasons.

Add Windows x86_64 and Linux x86 paths to generate-bindings

---

tools/src/bin/generate-bindings.rs

Currently when clang fails the panic print includes the debug representation of `ClangDiagnostic` which doesn't have newlines so it's really hard to read:
```
thread 'main' panicked at 'failed to generate bindings: ClangDiagnostic("H:/002_Mojurasu/projects/flipper/flipperzero-rs/tools/../../official/build/latest/sdk/f7_sdk/lib/STM32CubeWB/Drivers/CMSIS/Include/cmsis_compiler.h:278:4: error: Unknown compiler.\nH:\\002_Mojurasu\\projects\\flipper\\flipperzero-rs\\tools\\../../official/build/latest/sdk\\../../../toolchain/x86_64-windows/arm-none-eabi/include\\string.h:172:55: error: expected string literal in 'asm'\nC:\\Program Files\\LLVM\\lib\\clang\\12.0.0\\include\\emmintrin.h:4224:6: error: conflicting types for '_mm_clflush'\nC:\\Program …
```

Improve clang error readability

---

crates/flipperzero/src/macros.rs
crates/rt/src/manifest.rs
crates/sys/src/lib.rs
examples/hello-rust/src/main.rs

This allows using trailing comas in function-like macro calls.
This affects all public macros except for `entry!`
which generally looks like a good atrtibute-macro candidate.

feat: allow trailing comas in function-like macro calls

---

crates/.cargo/config.toml

This fixes build of `crates` module in Intellij-based IDEs.
Previous configuration would cause errors while trying to configure Cargo-based project.

build: fix build of `crates` inIntellij-based IDEs

---

crates/flipperzero/Cargo.toml
crates/flipperzero/src/furi/io.rs
crates/flipperzero/src/lib.rs
crates/flipperzero/src/macros.rs
crates/sys/Cargo.toml
crates/sys/src/furi.rs
examples/dialog/Cargo.lock
examples/gpio/Cargo.lock
examples/gui/Cargo.lock
examples/hello-rust/Cargo.lock
examples/hello-rust/src/main.rs
examples/notification/Cargo.lock

This is far more space efficent than `core::fmt`.
Removed `"\r\n"` hack, since console now handles `"\n"` correctly.
For example a `println!("Hello, {}", "Rust")` binary:
- `ufmt`: 972 B
- `core::fmt`: 4.03 KiB (325% larger)

Use `ufmt` crate for `print!` macros

---

.github/workflows/_build_and_test.yml
crates/.cargo/config.toml
crates/Cargo.toml
crates/cargo-runner.py
crates/flipperzero/Cargo.toml
crates/flipperzero/src/furi/message_queue.rs
crates/flipperzero/src/furi/sync.rs
crates/flipperzero/src/lib.rs
crates/flipperzero/tests/dolphin.rs
crates/sys/src/lib.rs
crates/test/Cargo.toml
crates/test/macros/Cargo.toml
crates/test/macros/src/deassert.rs
crates/test/macros/src/lib.rs
crates/test/src/lib.rs
tools/Cargo.lock
tools/Cargo.toml
tools/src/bin/run-fap.rs
tools/src/storage.rs

Test harness

---

tools/src/storage.rs

The `build-examples.py --install` script would fail on my Flipper with: "ERROR: file/dir not exist" because there was no Examples directory.
Make a small change to storage.rs to get the parent path on the Flipper SD card for the file to send, and create that directory before sending the file.
Converting between FlipperPaths and Paths or PathBufs is a pain, so just split from the last "/" character to get the parent path.

tools/storage: Create directory before sending file

---

crates/flipperzero/Cargo.toml
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/furi/string.rs
crates/flipperzero/src/furi/string/iter.rs
crates/flipperzero/src/furi/string/pattern.rs
crates/flipperzero/src/lib.rs
crates/flipperzero/tests/string.rs

`std::string::String` methods to be implemented:
- ~~`String::into_raw_parts(self) -> (*mut u8, usize, usize)`~~
- Doesn't make sense for `FuriString`. We could maybe expose `*mut sys::FuriString`?
- ~~`String::from_raw_parts(buf: *mut u8, length: usize, capacity: usize) -> String`~~
- We'd only expose this (via `unsafe`) if we want to leave `*mut sys::FuriString` exposed.
- ~~`String::from_utf8_unchecked(bytes: Vec<u8>) -> String`~~
- Doesn't make sense for `FuriString`.
- ~~`String::into_bytes(self) -> Vec<u8>`~~
- Doesn't make sense for `FuriString` (we aren't storing the string internally as a `Vec<u8>`, so it's better to just call `String::to_bytes().to_owned()`).
- ~~`String::as_str(&self) -> &str`~~
- ~~`String::as_mut_str(&mut self) -> &mut str`~~
- ~~`String::capacity(&self) -> …

Implement `String`-like wrapper around `FuriString`

---

crates/Cargo.toml
crates/test/Cargo.toml
crates/test/macros/Cargo.toml

`flipperzero-test 0.1.0` and `flipperzero-test-macros 0.1.0` have been published from d3f48ebeeb54ffac442740998bd1575c83ed819e. This should enable downstream users to write their own tests (maybe already, maybe with some future improvement PRs).

Updates to enable publishing test crates

---

crates/flipperzero/src/macros.rs

Now that `FuriString` exists, a convenience `format!` macro should also exist.

Add format! macro

---

crates/flipperzero/src/dialogs/mod.rs
crates/flipperzero/src/furi/message_queue.rs
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/furi/string.rs
crates/flipperzero/src/furi/string/pattern.rs
crates/flipperzero/src/furi/sync.rs
crates/flipperzero/src/furi/thread.rs
crates/flipperzero/src/storage.rs

This allows rust's null pointer optimization to kick in. For example, with this change the size of `Option<FuriString>` becomes 8 -> 4.
As far as I can tell, flipperzero's malloc doesn't ever return null but crashes the app instead.
See https://github.com/flipperdevices/flipperzero-firmware/blob/0.82.3/furi/core/memmgr_heap.c#L484
That's the function that `malloc` calls directly, it has the only return statement at the very end, and `furi_check` just crashes the app if the condition is false, i.e. the pointer is null.
I think I caught all the structs, I'm happy to add more if I didn't.

Use ptr::NonNull instead of raw pointers

---

tools/src/bin/serial_cli.rs

On MacOS with the default Terminal application, Crossterm reports the
`Ctrl + ]` sequence as `Ctrl + 5`. The `fbt` Python tool seems to work
fine on MacOS + Terminal app, so this may be a Crossterm quirk.
Capture the `Ctrl + 5` keycode and exit process.

serial_cli: capture exit keycode on MacOS terminal

---

crates/flipperzero/examples/view_dispatcher.rs

Add an example demonstrating a simple use of the ViewDispatcher module. This app switches between two views. A TextInput view that prompts the user to enter their name, and a Widget view that says hello to the name.

Add ViewDispatcher example

---

crates/rt/src/lib.rs
crates/rt/src/thread.rs

This tidies up the `entry!` macro and makes it easier to add other state cleanup functions later.

rt: Move thread waiter into a module

---

README.md
crates/flipperzero/src/furi/thread.rs
crates/sys/src/bindings.rs
docs/updating-sdk.md
tools/Dockerfile

https://github.com/flipperdevices/flipperzero-firmware/releases/tag/0.83.1
From what I can tell, it's a relatively large diff because the order of a lot of structs and functions got changed without any actual changes. Seems like the order of include paths got shuffled around a bit probably because of this item in the release notes:
- Libs: STM32CubeWB replaced with it's stand-lone, stripped version

Update bindings for firmware version 0.83.1

---

CHANGELOG.md
crates/test/macros/src/lib.rs

This is primarily to enable tests behind `#[cfg(feature = "alloc")]`, but may also be useful if we refactor to have services behind feature flags (https://github.com/flipperzero-rs/flipperzero/pull/29#discussion_r1059691569).

test: Support `#[cfg(..)]` attributes on test methods

---

crates/flipperzero/examples/dialog.rs
crates/flipperzero/examples/storage.rs
crates/flipperzero/src/dialogs/mod.rs
crates/flipperzero/src/furi/string.rs

Add a safe Rust wrapper for the dialog file browser methods and the
DialogsFileBrowserOptions type. Rename the DialogsApp::show() method
to show_message() and create new show_file_browser() method. Add a
getter method to FuriString to provide access to the inner
sys::FuriString via a raw pointer because a sys::FuriString is needed by
a few of the Furi C API functions. Extend the storage example to open a
file browser and have the user select the file that was just written to
the file system.
Note: The Furi C struct is named DialogsFileBrowserOptions, but all
other dialog types and functions are singular instead of plural. The
Rust type is named DialogFileBrowserOptions.
The DialogFileBrowserOptions type uses setter methods that return Self
so they can be chained together in the builder …

Dialogs app file browser wrapper

---

crates/flipperzero/examples/gpio.rs
crates/sys/src/inlines/furi_hal_gpio.rs

Also make register manipulations volatile as the original `furi` hal functions are.
Updated the GPIO example to verify that the actual state was being returned.

Fix gpio read always returning true

---

crates/flipperzero/src/furi/string.rs

`cargo doc` could not build the documentation when the `alloc` feature was disabled because it could not access `alloc` symbols.
This replaces them with direct links to the nightly documentation.

Fix cargo doc when not using the alloc feature

---

crates/test/macros/src/lib.rs
crates/test/src/lib.rs
tools/src/bin/run-fap.rs

This now enables test filtering:
```
$ cd crates/
$ cargo test -- FILTER ANOTHER_FILTER
```

Update test harness for upstream changes to loader

---

CHANGELOG.md
crates/flipperzero/src/furi/sync.rs
crates/flipperzero/src/furi/time.rs
crates/flipperzero/src/lib.rs

We approximately follow the APIs of `std::time::{Instant, Duration}`, adjusting for the wrapping clock as necessary.

Implement `flipperzero::furi::time::{Instant, Duration}`

---

CHANGELOG.md
crates/flipperzero/examples/dialog.rs
crates/flipperzero/examples/gui.rs
crates/flipperzero/examples/storage.rs
crates/flipperzero/examples/threads.rs
crates/sys/src/bindings.rs

It would probably good to make a dev branch for this as it has not been extensively tested. 
I used this awesome crate to play a bit with the flipper zero and it's really cool that this crate enables that without external bindings! Though the SDK Version was incompatible so i updated it. I also updated the documentation for some examples as I went through them

Upgrade to sdk 38.0

---

CHANGELOG.md
crates/flipperzero/examples/i2c-ds3231.rs
crates/flipperzero/src/gpio/i2c.rs
crates/flipperzero/src/gpio/mod.rs
crates/flipperzero/src/lib.rs

This adds a Rust API for using both the external and internal I2C bus with 7-bit addresses.

flipperzero: I2C interface

---

crates/flipperzero/Cargo.toml
crates/flipperzero/src/gpio/i2c.rs

Implements the I2C traits from embedded-hal, both the 0.2 and 1.0 rc1 versions.
Both implementations are optional features to avoid forcing the dependencies onto users.
Tested quickly using a logic analyzer and the [ssd1306 crate](https://crates.io/crates/ssd1306) with the following code:
```rust
use core::fmt::Write;
use ssd1306::prelude::*;
let bus = flipperzero::gpio::i2c::EmbeddedHalBus::new(
flipperzero::gpio::i2c::Bus::EXTERNAL,
flipperzero::furi::time::Duration::from_millis(100),
);
let interface = ssd1306::I2CDisplayInterface::new(bus);
let mut display = ssd1306::Ssd1306::new(interface, DisplaySize128x32, DisplayRotation::Rotate0)
.into_terminal_mode();
display.init().unwrap();
display.clear().unwrap();
display.write_str("Hello from the\nFlipper Zero\n").unwrap();
```

Add embedded-hal I2C traits implementations

---

CHANGELOG.md
crates/flipperzero/examples/dialog.rs
crates/flipperzero/examples/example_images.rs
crates/flipperzero/examples/gpio.rs
crates/flipperzero/examples/gui.rs
crates/flipperzero/examples/hello-rust.rs
crates/flipperzero/examples/i2c-ds3231.rs
crates/flipperzero/examples/notification.rs
crates/flipperzero/examples/storage.rs
crates/flipperzero/examples/threads.rs
crates/flipperzero/examples/view_dispatcher.rs
crates/rt/src/lib.rs
crates/test/macros/src/lib.rs
crates/test/src/lib.rs

The argument C string pointer is now handled internally instead of in user code.

rt: Change type signature of entry point to be safe

---

tools/src/bin/run-fap.rs

This prevents them from polluting the main `/ext` directory when a runner aborts partway through without deleting the tempdir.

tools: Create temporary directories under `/ext/.tmp`

---

crates/.cargo/config.toml
crates/flipperzero/src/furi/thread.rs
crates/flipperzero/src/gpio/i2c.rs
crates/flipperzero/src/lib.rs
crates/flipperzero/src/storage.rs
crates/rt/src/lib.rs
crates/rust-toolchain.toml
crates/sys/src/lib.rs
crates/test/macros/src/lib.rs

It doesn't *successfully* run the tests because Miri doesn't yet support FFI, but these changes enable the following command to actually start:
MIRI_NO_STD=1 cargo miri test --target thumbv7em-none-eabihf
Part of flipperzero-rs/flipperzero#100.

flipperzero: Enable Miri to start running the tests

---

.dockerignore
.github/workflows/_build_and_test.yml
.github/workflows/_lints.yml
.github/workflows/update_bindings.yml
.pinact.yaml
docs/updating-sdk.md
flake.nix
tools/Cargo.lock
tools/Dockerfile

This adds a new manual GitHub Action task capable of updating SDK version and creating a PR with the change.
This also pins dependency versions using `pinact` (which is supported by Dependabot) to ensure security.
This is built on top of #151

ci: enable automatic SDK Update PR creation

---

CHANGELOG.md
crates/flipperzero/src/dialogs/mod.rs
flake.lock

In #80 safe bindings for dialogs app file browser were added by @mogenson. At this moment, the native initialization function was unsound since it forgot to initialize one of the fields so we decided to perform initialization on Rust side.
Now that this issues is fixed in flipperdevices/flipperzero-firmware#2756 with the future guarantee to always initialize all fields we can (and should) migrate to this approach which is better for us from backwards compatibility standpoint since we will no longer have to reflect the changes to this structure on our side for sake of safety.
I've also added a `c_str` macro which has magically become `const`-friendly with the recent stabilization of `from_bytes_with_nul` which will land to stable soon (at least, by the time we are ready to become …

feat: make `DialogFileBrowserOptions::new()` use native initialization function

---

CHANGELOG.md
crates/flipperzero/src/furi/time.rs

Surprisingly, `Duration::MAX` was not the maximum possible duration.
`Duration::MAX` must be able to *contain* the delta between any two `Inteval` values, but not every `Duration` can be used with `Interval` (if `Duration > u32::MAX / 2` then we wouldn't be able to tell if the `Instant` was in the past or the future).

Fix `flipperzero::furi::time::Duration::MAX`

---

CHANGELOG.md
crates/flipperzero/src/furi/kernel.rs
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/furi/time.rs

This module exposes most of the `furi_kernel_*` APIs.
Centralizing these lets us remove a number of `unsafe` calls peppered across the codebase and allows things like providing optimized versions.

Add `flipperzero::furi::kernel` module

---

crates/flipperzero/src/furi/thread.rs

This removes the use of legacy `core::u32` constant which is depreceated and reported by Clippy.

chore: don't use legacy numeric constants

---

CHANGELOG.md
crates/flipperzero/src/furi/kernel.rs
crates/sys/src/furi.rs

Rather than a closure that takes a `Status`, take the status code. This allows easier chaining of types (e.g. `X::from`).
Follow-up from #180.

Change `Status::err_or_else` to use `Fn(i32) -> T`

---

CHANGELOG.md
crates/flipperzero/src/furi/kernel.rs
crates/flipperzero/src/furi/message_queue.rs
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/furi/sync.rs
crates/sys/src/furi.rs

This is an updated attempt at improving the ergonomics around working with `FuriStatus`. Rather than trying to use `sys::furi::Status` as a pseudo-`Error`/`Result` type, use a dedicated `Error` enum.
In a future PR I'm going to change how the bindings for `enum FuriStatus` to a newtype rather than integer constant. This will remove the need for a seperate `sys::furi::Status` type and the associated hoops required to turn that into a `Result` type. Being an alias for `i32` limits what traits or functions can be implemented on the type.

Add `sys::furi::Error` type for kernel errors

---

crates/flipperzero/Cargo.toml
crates/flipperzero/examples/stream_buffer.rs
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/furi/stream_buffer.rs
crates/flipperzero/src/furi/time.rs

Hey 👋🏻,
In this PR, I added some safe abstractions for the `FuriStreamBuffer`.
While working on it, I came across this note in the stream buffer implementation:
```
* ***NOTE***: Stream buffer implementation assumes there is only one task or
* interrupt that will write to the buffer (the writer), and only one task or
* interrupt that will read from the buffer (the reader).
```
So, I figured, why not enforce this constraint in the type system? The result is a split into a sender and receiver, similar to the `mpsc` channel in the standard library. They implement `Send`, so they can be moved between threads, but not `Clone` or `Sync`, making sure we only have one of each in a pair. Unfortunately, I had to use `Arc` to give ownership to both sides, which means this requires `alloc`. Other …

Add Safe Abstractions for `FuriStreamBuffer`

---

crates/flipperzero/src/furi/thread.rs

Furi provides access to [FreeRTOS Task Notification](https://freertos.org/Documentation/02-Kernel/02-Kernel-features/03-Direct-to-task-notifications/01-Task-notifications) feature which can be used for syncronization between threads.
Task notifications act as `u32` bitmask, so can be used to signal multiple potential interesting states on the target thread.

Provide safe wrappers for thread notification API

---

CHANGELOG.md
crates/sys/src/furi.rs

This is a simple `Box` implementation backed by the C heap for places where we can't assume that a global allocator has been defined.
For most users it is recommended to use `flipperzero-alloc` whenever dynamic allocation is required.

Add `flipperzero_sys::furi::Box`

---

CHANGELOG.md
crates/flipperzero/examples/example_images.rs
crates/flipperzero/examples/gui.rs
crates/flipperzero/examples/view_dispatcher.rs
crates/flipperzero/src/dialogs/mod.rs
crates/flipperzero/src/dolphin/mod.rs
crates/flipperzero/src/notification/mod.rs
crates/flipperzero/src/storage.rs
crates/sys/src/furi.rs
crates/test/src/lib.rs

This is safer and explicit about the static lifetime requirement.

Make `UnsafeRecord::open` take a `&'static CStr`

---

crates/flipperzero/src/furi/log/mod.rs

This would produce a "use of undeclared crate or module `ufmt`" error when compiling modules that didn't include `ufmt` on their own.

Fix missing `ufmt` in log macro scopes

---

CHANGELOG.md
crates/sys/src/lib.rs

Due to the way we called `__furi_crash_implementation` the value of the `r12` register would often get clobbered, corrupting the message.
This is fixed by directly jumping to the crash handler from inline assembly.
Only messages stored on flash memory can be shown at reboot, so strings stored in RAM (including string constants in external apps) will be replaced by a generic "check serial logs" message.
This also allows calling `halt!` and `crash!` in their no-argument form.

sys: Fix `halt!` and `crash!` message handling

---

CHANGELOG.md
crates/rt/src/panic_handler.rs

When connected via USB serial, there is often not enough time for the output to be fully recieved before the USB device resets.
Add a short 500 ms delay before we call `furi_crash`.
This also fixes incorrect `printf` formatting strings with explicit length (the length is provided as the 'precision' value after the decimal rather than the 'width' value before the decimal).

Fix display of panic message

---

.github/workflows/_build_and_test.yml
.github/workflows/_lints.yml

It looks like the `libudev-dev` package referenced in the CI scripts has been removed from the Ubuntu archive, causing CI/CD steps to fail. This can be fixed by explicitly calling `apt update` prior to installing packages.

Fix CI build failure caused by apt database

---

crates/alloc/src/lib.rs
crates/flipperzero/examples/view_dispatcher.rs
crates/flipperzero/src/furi/string/iter.rs
crates/rt/src/lib.rs
crates/rt/src/manifest.rs

Fix up several new warnings that appeared after enabling 2024 Edition lints.
The main cases here are:
- You need `unsafe` blocks around unsafe code, even in an `unsafe` function
- The `no_mangle` attribute need to be marked `unsafe`
- Prefer using `cast()` over `as *mut ...`

Fix additional 2024 Edition warnings

---

CHANGELOG.md
crates/flipperzero/examples/i2c-ds3231.rs
crates/flipperzero/examples/stream_buffer.rs
crates/flipperzero/src/furi/message_queue.rs
crates/flipperzero/src/furi/stream_buffer.rs
crates/flipperzero/src/furi/sync.rs
crates/flipperzero/src/furi/thread.rs
crates/flipperzero/src/furi/time.rs
crates/flipperzero/src/gpio/i2c.rs

This is to prevent confusion between the two similar but not interchangeable types.

Rename `Duration`/`Instant` to `FuriDuration`/`FuriInstant`

---

CHANGELOG.md
crates/flipperzero/examples/notification.rs
crates/flipperzero/src/dialogs/mod.rs
crates/flipperzero/src/dolphin/mod.rs
crates/flipperzero/src/furi/hal.rs
crates/flipperzero/src/furi/hal/power.rs
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/notification/mod.rs
crates/flipperzero/src/storage.rs
crates/sys/src/furi/record.rs

This PR adds `Clone` support to `UnsafeRecord` so that it can be used for reference-counting patterns and adds `Clone` for the existing Record handles.
Additionally it adds handles for `Power` and `Storage` services.

Additional Records

---

CHANGELOG.md
crates/build-examples.py
crates/flipperzero/examples/serial-echo.rs
crates/flipperzero/src/furi/event_flag.rs
crates/flipperzero/src/furi/mod.rs
crates/flipperzero/src/lib.rs
crates/flipperzero/src/serial.rs

This provides access to the serial interface using an async worker to safely transfer received bits from the interrupt handler to the application.
Add a simple serial echo example and wrapper for `FuriEventFlag` that can be used to wait for an event without polling.

Add serial support.

---

CHANGELOG.md
crates/build-examples.py
crates/flipperzero/Cargo.toml
crates/flipperzero/examples/embedded-graphics.rs
crates/flipperzero/src/furi/event_flag.rs
crates/flipperzero/src/gui/canvas.rs
crates/flipperzero/src/gui/mod.rs

This allows using `Canvas` as an `embedded-graphics` draw target. It requires the `embedded-graphics` feature which is enabled by default.
Also included is an `embedded-graphics` example based on the embedded-graphics "Hello world" example.
I kept the `Gui` API wrappers fairly minimal so they don't disrupt #29.

Add embedded-graphics driver

---

CHANGELOG.md
crates/flipperzero/src/gui/mod.rs

To get mutable access to a `Canvas` reference you must first call `gui_direct_draw_acquire` then release it with `gui_direct_draw_release` when done.
In our Rust wrapper, this is enforced by returning an `ExclusiveCanvas` handle which represents the claim and can be use for borrowing a `Canvas`.
As such, the following should not compile (temporary value dropped while borrowed):
```rust
let canvas: &mut Canvas = gui.direct_draw_acquire().canvas_mut();
````
However, before this fix it did, due to the borrow happening on `Gui` and not `ExclusiveCanvas`. This would make it impossible to actually write to the Canvas, which was part of the issue in #235.
`ExclusiveCanvas` uses `PhantomData` to hold a "reference" to `Gui`, so by holding a reference to `ExclusiveCanvas` we transitively also hold …

Fix lifetime of `ExclusiveCanvas` canvas references
